# Generated by Django 3.2.4 on 2021-06-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortner',
            options={},
        ),
    ]
