# Generated by Django 3.2.4 on 2021-06-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_alter_shortner_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortner',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
