# Generated by Django 3.2.4 on 2021-06-12 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0004_auto_20210612_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortner',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='shortner',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
