# Generated by Django 3.2.4 on 2021-06-12 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0005_auto_20210612_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortner',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='shortner',
            name='updated',
        ),
        migrations.AlterField(
            model_name='shortner',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
