# Generated by Django 3.2.4 on 2021-06-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0006_auto_20210612_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortner',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
